spring:
  profiles:
    active: local
server:
  port: 8081

---
spring:
  profiles: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: lib-event-consumer

---
spring:
  profiles: dev
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: lib-event-consumer

---

spring:
  profiles: test
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: lib-event-consumer

---


spring:
  profiles: preprod
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: lib-event-consumer

---



spring:
  profiles: prod
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: lib-event-consumer








